### ISSUE TITLE
GEOS : Weekly PM Meeting Agenda 2022

### ISSUE THREAD

**Issue by PLoiya** [hackforla/GreenEarthOS#101]
### Overview
We need an agenda for the coming meeting and notes about what happens during the meetings so we can stay on track

### Action Items
- [ ] Add items for the agenda to comments at the bottom, or into the next week's agenda if it's available
- [ ] Add link to agenda's past to the Resources section below
- [ ] Create new agendas for the team by copying template below

```
## Date Agenda and notes

### Prework
- [ ] issue for audit #31

### Roll Call
- [ ] Bonnie
- [ ] Puneet
- [ ] Joanna

#### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/GreenEarthOS/projects/1#column-15327305)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/GreenEarthOS/issues/assigned/ExperimentsInHonesty)
       - [ ] [Puneet](https://github.com/hackforla/GreenEarthOS/issues/assigned/PLoiya)
       - [ ] [Sweta](https://github.com/hackforla/GreenEarthOS/issues/assigned/ssweta)
       - [ ] [Joanna](https://github.com/hackforla/GreenEarthOS/issues/assigned/joval604)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further

#### New Items
- [ ] 
- [ ] Carry forward anything we didn't have time for 

### FYIs

### Notes from meeting

### Task Items

### Items for next weeks Agenda

```

### Prior meetings
[2022-01-21](https://github.com/hackforla/GreenEarthOS/issues/101#issuecomment-1019016503)

**Comment by PLoiya** [comment]
## 20220121 Agenda and notes

### Prework
- [ ] issue for audit #31

### Roll Call
- [ ] Bonnie
- [ ] Puneet
- [ ] Joanna

#### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/GreenEarthOS/projects/1#column-15327305)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/GreenEarthOS/issues/assigned/ExperimentsInHonesty)
       - [ ] [Puneet](https://github.com/hackforla/GreenEarthOS/issues/assigned/PLoiya)
       - [ ] [Sweta](https://github.com/hackforla/GreenEarthOS/issues/assigned/ssweta)
       - [ ] [Joanna]()
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further

#### New Items
- [ ] 
- [ ] Carry forward anything we didn't have time for 

### FYIs

### Notes from meeting

### Task Items

### Items for next weeks Agenda

**Comment by ExperimentsInHonesty** [comment]
## 2022-02-04 Agenda and notes

### Prework
- [ ] issue for audit #31

### Roll Call
- [ ] Bonnie
- [ ] Puneet
- [ ] Joanna

#### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/GreenEarthOS/projects/1#column-15327305)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/GreenEarthOS/issues/assigned/ExperimentsInHonesty)
       - [ ] [Puneet](https://github.com/hackforla/GreenEarthOS/issues/assigned/PLoiya)
       - [ ] [Sweta](https://github.com/hackforla/GreenEarthOS/issues/assigned/ssweta)
       - [ ] [Joanna]()
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further

#### New Items
- [ ] 
- [ ] Carry forward anything we didn't have time for 

### FYIs

### Notes from meeting

### Task Items

### Items for next weeks Agenda

**Comment by joval604** [comment]
## 2022-02-11 Agenda and notes

### Prework
- [x] issue for audit #31

### Roll Call
- [x] Bonnie
- [ ] Puneet
- [x] Joanna

#### Recurring items: 
 - [x] review any issues that are in the [new issue approval column] (https://github.com/hackforla/GreenEarthOS/projects/1#column-15327305)
 - [ ] Accountability and Support Check.
    - [x] Review assignments for each PM
       - [x] [Bonnie](https://github.com/hackforla/GreenEarthOS/issues/assigned/ExperimentsInHonesty)
       - [x] [Puneet](https://github.com/hackforla/GreenEarthOS/issues/assigned/PLoiya)
       - [x] [Sweta](https://github.com/hackforla/GreenEarthOS/issues/assigned/ssweta)
       - [x] [Joanna](https://github.com/hackforla/GreenEarthOS/issues/assigned/joval604)
- [x] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further

#### New Items
- [ ] Ask Punette if he has heard from Sweta and if she is off the project we need to close out her issues or put them in the prioritized backlog. https://github.com/hackforla/GreenEarthOS/issues/assigned/ssweta
- [ ] Help Punette remove himself from some issues, so that its a reasonable number
- [ ] Carry forward anything we didn't have time for 

### FYIs

### Notes from meeting
 

### Task Items

### Items for next week's Agenda

**Comment by rpradheap** [comment]
Agenda  for April 29,2022

- [ ] General training  ( Q&A)
- [ ]  Talk about the activity to do in next meeting
- [ ] how to estimate story points for example Designing the image for Hacker La website for GreenEarthOS Project
