### ISSUE TITLE
2-9-2022 Weekly Team Meeting

### ISSUE THREAD

**Issue by joval604** [hackforla/GreenEarthOS#105]
### Overview
We need an agenda for the coming meeting and notes about what happens during the meetings so we can stay on track

### Action Items
- [ ] Add items for the agenda to comments at the bottom, or into the next week's agenda if it's available
- [ ] Add link to agenda's past to the Resources section below
- [ ] Create new agendas for the team by copying template below

```
## Date Agenda and notes

### Prework
- [ ] 

### Roll Call
- [ ] Bonnie
- [ ] Puneet
- [ ] Joanna

#### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/GreenEarthOS/projects/1#column-15327305)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/GreenEarthOS/issues/assigned/ExperimentsInHonesty)
       - [ ] [Puneet](https://github.com/hackforla/GreenEarthOS/issues/assigned/PLoiya)
       - [ ] [Sweta](https://github.com/hackforla/GreenEarthOS/issues/assigned/ssweta)
       - [ ] [Joanna]()
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further

#### New Items
- [ ] 
- [ ] Carry forward anything we didn't have time for 

### FYIs

### Notes from meeting

### Task Items

### Items for next weeks Agenda

```

### Prior meetings
[2022-01-19](https://github.com/hackforla/GreenEarthOS/issues/100#issuecomment-1017077194)
