### ISSUE TITLE
Organize project using issues, milestones and labels

### ISSUE THREAD

**Issue by angle-zhang** [hackforla/GreenEarthOS#31]
### Overview
We need to organize open issues and add the appropriate labels and milestones so that we can easily manage the project by seeing where any specific initiative is at any given time, and who to recruit for, etc.

### Action Items
- [x] Add labels
   - [x] size: 1pt  (use 1,2,3,5,8,13+) 
- [ ] prioritize issues for certain milestones
- [ ] Make sure that all issues have missing labels if they need them.

### Resources/Instructions
https://github.com/hackforla/GreenEarthOS/labels
Civic Tech Example on sizing - https://github.com/civictechindex/CTI-website-frontend/labels?q=size

#### Should be 0/0
- [All the issue with a size or size missing label excluded](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aissue+is%3Aopen+-label%3A%22size%3A+1pt%22+-label%3A%22size%3A+2pt%22+-label%3A%22size%3A+3pt%22+-label%3A%22size%3A+5pt%22+-label%3A%22size%3A+8pt%22+-label%3A%22size%3A+13pt%22+-label%3A%22size%3A+missing%22+)
- [All the issues with role or role missing label excluded](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aopen+is%3Aissue+-label%3A%22role%3A+missing%22+-label%3A%22role%3A+Backend+Developer%22+-label%3A%22role%3A+business+analyst%22+-label%3A%22role%3A+data+analyst%22+-label%3A%22role%3A+data+scientist%22+-label%3A%22role%3A+marketing%22+-label%3A%22role%3A+product+management%22+-label%3A%22role%3A+product+owner%22+-label%3A%22role%3A+UI%2FUX+designer%22+-label%3A%22role%3A+UI%2FUX+researcher%22)
- [All the issues with buckets or bucket missing label excluded](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aopen+is%3Aissue+-label%3A%22Bucket%3A+missing%22+-label%3A%22Bucket%3A+All%22+-label%3A%22Bucket%3A+Climate+Collabathon%22+-label%3A%22Bucket%3A+Climate+projects%22+-label%3A%22Bucket%3A+Ecosystem+Map%22+-label%3A%22Bucket%3A+Climate+Conferences%22)
- [All the issues with Milestone or milestone missing label excluded](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone+-label%3A%22milestone%3A+missing%22)

#### count them
- [All the issues with the size missing label](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aissue+is%3Aopen+label%3A%22size%3A+missing%22) 
- [All the issue with the role missing label](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aopen+is%3Aissue+label%3A%22role%3A+missing%22)
- [All the issues with the bucket missing label](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aissue+is%3Aopen+label%3A%22Bucket%3A+missing%22)
- [All the issues with the milestone missing label](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone)
- [Issues that have not yet been added to the project board](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aissue+is%3Aopen+no%3Aproject)

- Number of issues in the new issue approval column

**Comment by angle-zhang** [comment]
Priority for the next meeting

**Comment by PLoiya** [comment]
All issues are labeled with size, so moving this item for the review. 

Need to followup to identify new labels if required.

**Comment by ExperimentsInHonesty** [comment]
All the issues with the size missing label: 4
All the issue with the role missing label: 4
All the issues with the bucket missing label: 26

**Comment by ExperimentsInHonesty** [comment]
2022-01-19
Size 5/0
Role 4/9
Bucket 30/20

**Comment by ExperimentsInHonesty** [comment]
Size: 3/1
role: 2/10
bucket: 26/22
Milestone: 23/24
Issues with no project: 0/0

**Comment by joval604** [comment]
Size: 3/1
role: 1/10
bucket: 25/22
Milestone: 22/26
Issues with no project: 0/0
Number of issue in new issue approval column: 3
