### ISSUE TITLE
GEOS: GreenEarthOS Meeting Agenda 2021

### ISSUE THREAD

**Issue by PLoiya** [hackforla/GreenEarthOS#76]
### Overview
This issue tracks the weekly agenda for the GreenEarthOS project with team that is scheduled on Wed and the other meeting between Product managers that is scheduled on Friday.

### Weekly Agenda

   - Team Meeting - Week of Dec 26, 2021
   - PM Meeting - Week of Dec 26, 2021
   - Team Meeting - Week of Dec 19, 2021
   - PM Meeting - Week of Dec 19, 2021
   - Team Meeting - Week of Dec 12, 2021
   - PM Meeting - Week of Dec 12, 2021
   - Team Meeting - Week of Dec 05, 2021
   - PM Meeting - Week of Dec 05, 2021
   - Team Meeting - Week of Nov 28, 2021
   - PM Meeting - Week of Nov 28, 2021
   - Team Meeting - Week of Nov 21, 2021
   - PM Meeting - Week of Nov 21, 2021
   - Team Meeting - Week of Nov 14, 2021
   - PM Meeting - Week of Nov 14, 2021
   - Team Meeting - Week of Nov 07, 2021
   - [PM Meeting - Week of Nov 07, 2021](https://github.com/hackforla/GreenEarthOS/issues/76#issuecomment-966362957)
   - Team Meeting - Week of Oct 31, 2021
   - PM Meeting - Week of Oct 31, 2021
   - Team Meeting - Week of Oct 24, 2021
   - PM Meeting - Week of Oct 24, 2021
   - [Team Meeting - Week of Oct 17, 2021](https://github.com/hackforla/GreenEarthOS/issues/76#issuecomment-948184765)
   - PM Meeting - Week of Oct 17, 2021
   - Team Meeting - Week of Oct 10, 2021
   - PM Meeting - Week of Oct 10, 2021
   - Team Meeting - Week of Oct 03, 2021
   - [PM Meeting - Week of Oct 03, 2021](https://github.com/hackforla/GreenEarthOS/issues/76#issuecomment-937401990)
   - [Team Meeting - Week of Sep 26, 2021](https://github.com/hackforla/GreenEarthOS/issues/76#issuecomment-930281382)
   - PM Meeting - Week of Sep 26, 2021
   - [Team Meeting - Week of Sep 19, 2021](https://github.com/hackforla/GreenEarthOS/issues/76#issuecomment-925452121)
   - [PM Meeting - Week of Sep 19, 2021](https://github.com/hackforla/GreenEarthOS/issues/76#issuecomment-922593944)
   - [Team Meeting - Week of Aug 22, 2021](https://github.com/hackforla/GreenEarthOS/issues/76#issuecomment-922592616)
   - [PM Meeting - Week of Aug 22, 2021]
   - [Team Meeting - Week of Aug 15, 2021](https://github.com/hackforla/GreenEarthOS/issues/76#issuecomment-922591894)
   - [PM Meeting - Week of Aug 15, 2021]

**Comment by PLoiya** [comment]
Agenda for the week of Aug 15, 2021 

> 

>

**Comment by PLoiya** [comment]
Agenda for the week of Aug 22, 2021 

> - Review the issue on recruiting UI/UX designer. Do we need more resources as Maria has joined us.
> - Work with Bonnie on the deck (Roadmap)
> - Alignment on the Weekly PM Meeting time

**Comment by PLoiya** [comment]
Agenda for the week of Sep 19, 2021 (PM Meeting) : 

> - Review MKDOC issue with Jason/Bonnie
> - Review draft copy of Strategy and Roadmap

**Comment by PLoiya** [comment]
Agenda for the week of Sep 19, 2021 (Team Meeting) :

> Review the logo design created by Maria
> Check with Bonnie if we need UI/UX researcher

**Comment by PLoiya** [comment]
Agenda for the week of Sep 26, 2021 (Team Meeting on 29 Sep) :
- Review the logo design with Maria
- Review the comments provided by Gillian on the interview script. [issue](https://github.com/hackforla/GreenEarthOS/issues/44)
- Review the PRD document created by Puneet as part of the [issue](https://github.com/hackforla/GreenEarthOS/issues/68)

**Comment by PLoiya** [comment]
Agenda for the week of Nov 14, 2021 (Team Meeting) :

- Branding exercise with team

**Comment by ExperimentsInHonesty** [comment]
Agenda for 12/17/21

### Prework
- [ ] issue for audit #31

### Roll Call
Sweta, Bonnie, Puneet

#### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/GreenEarthOS/projects/1#column-15327305)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/GreenEarthOS/issues/assigned/ExperimentsInHonesty)
       - [ ] [Puneet](https://github.com/hackforla/GreenEarthOS/issues/assigned/PLoiya)
       - [ ] [Sweta](https://github.com/hackforla/GreenEarthOS/issues/assigned/ssweta)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further

#### New Items

#### Notes

#### Task Items

**Comment by ExperimentsInHonesty** [comment]
Agenda for 12/21/21

### Prework
- [x] issue for audit #31

### Roll Call
Bonnie, Puneet

#### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/GreenEarthOS/projects/1#column-15327305)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each PM
       - [ ] [Bonnie](https://github.com/hackforla/GreenEarthOS/issues/assigned/ExperimentsInHonesty)
       - [ ] [Puneet](https://github.com/hackforla/GreenEarthOS/issues/assigned/PLoiya)
       - [ ] [Sweta](https://github.com/hackforla/GreenEarthOS/issues/assigned/ssweta)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label](https://github.com/hackforla/GreenEarthOS/issues?q=is%3Aopen+is%3Aissue+label%3Aepic) and define how to break down further

#### New Items
- [ ] change label from climate events to climate conferences
- [ ] Did Sweta make her issue, and do any updates on the wiki?  If not, carry over to next meeting
- [ ] Did Bonnie update the audit issue, and make a second issue specifically for Climate Conferences issues

#### Notes


#### Task Items

**Comment by PLoiya** [comment]
created 2022 agenda list.
