### ISSUE TITLE
Images for GreenEarthOS initiative

### ISSUE THREAD

**Issue by PLoiya** [hackforla/GreenEarthOS#81]
### Overview
We need to find/discover/develop few images that can help connecting people to the GreenEarthOS initiatives. 

### Action Items
- [ ] Make issues
#### Issue 1
- [ ] Identify climate images (make sure you use only creative commons)
- [ ] store the images with the following info in this issue https://github.com/hackforla/GreenEarthOS/issues/15
  - [ ] source url
  - [ ] author
  - [ ] license
- [ ] Divide them into positive & negative images

#### Issue 2
- [ ] Setup usabilityhub or other tool to identify words or emotions that people associate with them and which image is likely to make them want to contribute

#### Issue 3
Dependencies
 - (hackforla having non profit status under civictechstructure)
 - Issue 1
 - Issue 2
  - [ ] setup donate button
  - [ ] test different images and words with users by asking for donations of $1 across several platforms (twitter, facebook, instagram)

#### Issue 4
  - [ ] Synthesize findings
  - [ ] Review findings with team
  - [ ] Determine Next steps
