### ISSUE TITLE
Roadmap: Events

### ISSUE THREAD

**Issue by ssweta** [hackforla/GreenEarthOS#84]
### Overview
We need to create a roadmap so that we can deliver our product to market.

### Action Items

- [ ] Review the guides team roadmap.
- [ ] Create a spreadsheet in the project drive 
- [ ] Add a link to the spreadsheet in the resources section below
- [ ] Brainstorm objectives
- [ ] Prioritize objectives
- [ ] Create names for milestones
- [ ] Define what is needed in order to achieve objectives
- [ ] Create Labels

### Resources/Instructions
[Guides team roadmap](https://docs.google.com/spreadsheets/d/1xYUlIKsfE2-CeExIQ8i3oLD8pC7hjMTPM2YLSMFA8_s/edit#gid=0)

[Project Google Drive](https://drive.google.com/drive/folders/1QAKybsP5L9wRWmY8MYj7AaD3rnDTf_n8?usp=sharing)

[Climate Event Roadmap](https://docs.google.com/spreadsheets/d/1NJjIcvL44ouUDG5teu4Bvqux5W_n5CYqcoeFU6wWVx8/edit#gid=0)

**Comment by ssweta** [comment]
Gave my first stab, need to understand if I'm in the right direction.
Also, need an understanding of current status

**Comment by ssweta** [comment]
Refined the Climate Event Roadmap - need understanding on compliance and security
Created Webpage requirements - needs review.
Added [issue 85](https://github.com/hackforla/GreenEarthOS/issues/85) as suggested - needs review 
Website Logo - few ideas to be discussed

**Comment by ssweta** [comment]
Edited Climate Event Roadmap
Need input from UXR for website solutioning
Created CE [Onesheet](https://docs.google.com/document/d/1a2QUorc_V0Cj6mARQNR60urzYAj1vOU9p_ceom2ec54/edit?usp=sharing) - please review

**Comment by ExperimentsInHonesty** [comment]
next steps after last item
usability testing
refinement
marketing/placement

**Comment by ExperimentsInHonesty** [comment]
make the feature labels

**Comment by ssweta** [comment]
Edited  [Onesheet](https://docs.google.com/document/d/1a2QUorc_V0Cj6mARQNR60urzYAj1vOU9p_ceom2ec54/edit)
Created[ issue for C&C analysis, assigned to Michelle](https://github.com/hackforla/GreenEarthOS/issues/88)
Refined the [Climate Event Roadmap](https://docs.google.com/spreadsheets/d/1NJjIcvL44ouUDG5teu4Bvqux5W_n5CYqcoeFU6wWVx8/edit#gid=664343742)

**Comment by ExperimentsInHonesty** [comment]
Here is the location to create new labels: https://github.com/hackforla/GreenEarthOS/labels
next week, ill look at the onesheet for cc revisions

**Comment by ssweta** [comment]
Edited onesheet
feature labels created using the link provided

**Comment by PLoiya** [comment]
Bonnie made few changes on the one sheet - 
- Updated the footer date
- Updated with the website
- Few edits on the text

**Comment by PLoiya** [comment]
After converting one sheet to PDF, it needs to be updated on Hackforla and GreenEarthOS website. @ssweta please move the file to Project Overview folder and create the pdf version.

**Comment by ssweta** [comment]
Created pdf version. Word and pdf both saved in project overview folder under published version folder.

**Comment by ExperimentsInHonesty** [comment]
Please review the labels that you made.  I see some that are missing the proper formatting, such as 
personas
Impact interview
expert interviews

See how they need to be written in the roadmap (see below for examples)
feature: Onesheet
feature: Comparative Analysis
feature: Impact interview
feature: Usability Testing
feature: Expert Interviews
feature: Personas
feature: Surveyfeature: Analytics
feature: Usability Testing
feature: Survey
p-feature: Website Content
feature: Usability Testing
feature: Expert Interview
feature: Survey

**Comment by PLoiya** [comment]
`
<img width="1059" alt="Screenshot 2021-12-21 at 6 49 16 PM" src="https://user-images.githubusercontent.com/80374934/147012131-4307ae4f-7b38-438c-95f9-f831259d4064.png">

<img width="1056" alt="Screenshot 2021-12-21 at 6 48 53 PM" src="https://user-images.githubusercontent.com/80374934/147012136-12bc18fa-01e7-4302-86d9-27ef3772817a.png">

`

**Comment by ExperimentsInHonesty** [comment]
@ssweta Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA
